language: c

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - sudo apt-get install -y libgsl0-dev libgmp-dev gcc-4.8 g++-4.8 c2hs
  - sudo ln -fs /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -fs /usr/bin/g++-4.8 /usr/bin/g++
  - stack setup

script:
  - stack build
