sudo: false
language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libgsl0-dev
            - libgmp-dev
            - c2hs
      env: GCC=gcc-4.9

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export ARGS="--no-terminal --ghc-options=-pgmc=$GCC"

install:
  - stack --install-ghc build $ARGS

script:
  - stack build $ARGS
